image: ubuntu:focal

before_script:
  - apt-get -qq update
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -qq install python3-pip gcovr g++ cmake
  - pip3 -q install --upgrade pip
  - pip -q install conan
  - conan config install conan/config/

test:
  stage: test
  script:
    - conan install . -if build/ -s build_type=Release
    - conan build . -bf build/
    - conan export . spiessensm/testing
    - conan test test_package Flow/2.0@spiessensm/testing -s build_type=Release
    - conan install test_package/ -if coverage/ -s build_type=Debug -o coverage=True
    - conan build test_package/ -bf coverage/
    - gcovr coverage/

package:
  stage: deploy
  script:
    - conan install . -if build/ -s build_type=Release
    - conan build . -bf build/
    - conan export . spiessensm/dev
    - conan remote add spiessensm https://gitlab.com/api/v4/projects/24373418/packages/conan
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan remove Flow/2.0@spiessensm/dev --remote=spiessensm
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload Flow/2.0@spiessensm/dev --all --remote=spiessensm

release:
  stage: deploy
  only:
    - tags
  script:
    - conan install . -if build/ -s build_type=Release
    - conan build . -bf build/
    - conan export . spiessensm/stable
    - conan remote add spiessensm https://gitlab.com/api/v4/projects/24373418/packages/conan
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload Flow/${CI_COMMIT_TAG}@spiessensm/stable --all --remote=spiessensm
